### ISSUE TITLE
💖 looking for hetznercloud driver maintainers

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule-hetznercloud#10]
I am unable to maintain this driver as I am not using it, so I am looking for maintainers. 

I can keep providing support for integration with molecule itself but not around vagrant bits.

I would work noting that the top priority would be to setup CI jobs.

**Comment by ssbarnea** [comment]
@decentral1se I added you back to the project, in fact I lost access myself during the migration.

**Comment by decentral1se** [comment]
I am going to take over maintenance of this but at https://git.autonomic.zone/autonomic-cooperative/molecule-hetznercloud. I will use this as a mirror to push updates to. I'll respond on this issue tracker if needed. If anyone wants to run it from Github side, freel free to take over.

**Comment by ssbarnea** [comment]
I never used them, do they have a GitHub App to integrate it as a 3rd party CI? I doubt we would have issues using yet another CI/CD.

**Comment by gundalow** [comment]
@decentral1se Hey, good to hear from you again. 
Not heard of Drone CI/CD before, though it looks cool.
I see they do have GitHub integration https://docs.drone.io/server/provider/github/

@decentral1se If we enable Drone CI/CD for ansible-community/molecule-hetznercloud would that work for you? Avoids needing to work across two forks of code/issues/PRs which will hopefully make your life easier.

**Comment by decentral1se** [comment]
No thanks. What is easier for me is doing what I said in https://github.com/ansible-community/molecule-hetznercloud/issues/10#issuecomment-618909405. Now that there is a maintainer, I'm closing this off. If anyone wants to join in, please open an issue or ping me on IRC.

**Comment by gundalow** [comment]
Excellent. Please shout out if we can help with anything.
