### ISSUE TITLE
Too strict molecule dependency

### ISSUE THREAD

**Issue by xoxys** [ansible-community/molecule-hetznercloud#115]
Hi, is there a reason to use this very strict [version range](https://github.com/ansible-community/molecule-hetznercloud/blob/main/setup.py#L49) for molecule? As molecule is released quite frequently, the plugin breaks quite often until a new release was tagged.

**Comment by jooola** [comment]
I just released a new version of the plugin that support the latest version of molecule.

**Comment by xoxys** [comment]
> I hope this answers your question, let me know you think we should reconsider my decision.

Fair point, makes sense, thanks!
