### ISSUE TITLE
pypi issue tracker point to private tracker instance

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule-hetznercloud#15]
I discovered that the issue tracker listed on https://pypi.org/project/molecule-hetznercloud/ points to https://git.autonomic.zone/autonomic-cooperative/molecule-hetznercloud/issues where I want not able to login or to create an account.

![](https://sbarnea.com/ss/Screen-Shot-2020-06-14-15-03-22.12.png)

Please address this issue as molecule-hetznercloud is causing some problems with molecule packaging.

**Comment by decentral1se** [comment]
Hmmm, I see. I guess it should point here where you can make an account freely.

**Comment by ssbarnea** [comment]
The experience with the first visit was a frustrating one because not only that it does not support login with a popular service like github, google, facebook, but also it does not have any indication in how to create an account. For dev tools, using github to login became kinda standard.

PS. OpenID seems pretty much dead these days.
