### ISSUE TITLE
Setup functional testing

### ISSUE THREAD

**Issue by decentral1se** [ansible-community/molecule-hetznercloud#2]
Need to chat to Hetzner Cloud world to get the CI running over here.

**Comment by decentral1se** [comment]
@LKaemmerling, hey again, we're working on moving the drivers out (more pluggable architecture) of Molecule for 3.0 and I need to transfer the CI configuration over here. I think that needs some arrangement on your side or? I will continue to use the same token, is it OK?

**Comment by LKaemmerling** [comment]
@decentral1se yep, I need to add the new repository and remove the old one. The CI on the old one will not work then, would it make sense to add a new key?

**Comment by LKaemmerling** [comment]
@decentral1se @ssbarnea is there a plan to push this forward?

**Comment by decentral1se** [comment]
Hey @LKaemmerling, not from my side. Someone will have to pick it up.
