### ISSUE TITLE
Volume clean up does not delete attached volumes

### ISSUE THREAD

**Issue by decentral1se** [ansible-community/molecule-hetznercloud#24]
See https://github.com/ansible-collections/hetzner.hcloud/issues/47.

/cc @xoxys

**Comment by xoxys** [comment]
Pretty sure it is expected to not auto delete the volume as it can be reused and attached to a different server. Maybe some kind of fore option is possible.

**Comment by xoxys** [comment]
Wait my fault... You were talking about the hcloud_volume module... In this case, I agree 
:D

**Comment by decentral1se** [comment]
Yeah I guess for the testing use case, you want to tear down all resources afterwards.

Let's see what comes out of that ticket upstream.

**Comment by decentral1se** [comment]
OK, looks like it is on our end, need to investigate:

> https://github.com/ansible-collections/hetzner.hcloud/issues/47#issuecomment-757674817

**Comment by xoxys** [comment]
I'm a bit confused as I'm using this construct since a while with the delegated driver in molecule without issues. As the servers were deleted first volumes should be unattached already if the `hetzner_volume` absent task is running.

**Comment by decentral1se** [comment]
Hmmmm yeah weird...best reply as response to https://github.com/ansible-collections/hetzner.hcloud/issues/47#issuecomment-757674817? Don't have time to dig into this right now...

**Comment by LKaemmerling** [comment]
As i wrote in the initial issue, i think the problem is that the state is not correct to set to `absent`. I say present, otherwise, it would go through the "detaching" step.

**Comment by decentral1se** [comment]
Hmmm, it seems like we need to first then detach the volumes, delete the instances and then run the delete of the volumes again to finally fully delete them. It seems the [current logic](https://github.com/ansible-community/molecule-hetznercloud/blob/main/molecule_hetznercloud/playbooks/destroy.yml) of first deleting the instance with the still attached volumes (it is actually working for me but I see not for @cwaninger) is getting the volumes into a weird state!?  Good point regard `delete_protection`, we should ensure that is disabled for testing runs. I will try to fix this shortly.

**Comment by decentral1se** [comment]
I don't quite understand your comments in https://github.com/ansible-community/molecule-hetznercloud/issues/24#issuecomment-758438169 @LKaemmerling, are you referring to https://github.com/ansible-community/molecule-hetznercloud/blob/main/molecule_hetznercloud/playbooks/destroy.yml? Because I don't see how setting that to `present` would help? Also re: https://github.com/ansible-collections/hetzner.hcloud/issues/47#issuecomment-757674817 the `server` is not empty and the volume is technically not still attached since the instance is first deleted? I will take another look.

**Comment by decentral1se** [comment]
Quite confused now :scream: https://github.com/ansible-collections/hetzner.hcloud/issues/84#issuecomment-851470353

**Comment by decentral1se** [comment]
Annnnd back to me/"us" :joy: https://github.com/ansible-collections/hetzner.hcloud/issues/84#issuecomment-869684883

**Comment by decentral1se** [comment]
Ok, the saga continues but https://github.com/ansible-collections/hetzner.hcloud/issues/47#issuecomment-881283218 happened! So it looks like this is something that will help when we can move to the new version. I am still stuck for time but I if anyone has spoons, this could be fixable now.
