### ISSUE TITLE
Pending removal of driver unless a maintainer step in

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule-hetznercloud#36]
Few minutes ago I observed that this driver does not have any CI/CD pipeline configured and thus I will soon remove it from the list of drivers as molecule cores are not able to maintain CI for this driver.

I will manually merge the hotfix this time but if nobody steps in to takeover maintenance and setup CI pipelines for it that report on pull requests, I will mark it abandoned and remove from molecule own testing pipeline (eco job).

I hope someone steps in.

**Comment by decentral1se** [comment]
CI/CD is in https://drone.autonomic.zone/autonomic-cooperative/molecule-hetznercloud?

**Comment by ssbarnea** [comment]
IMHO, documenting that somewhere something is running does not provide enough confidence. I see no checks running on pull requests and I know that all modern CI are able to report check status on github so maintainer can avoid merging broken changes.

Ideally all projects should also require one peer review before merging but I am aware that this may be a real problem for very small projects (like ones with one maintainer).

Any change to address the missing checks issue?

**Comment by decentral1se** [comment]
It is best effort right now. You can open a ticket with a spec of what you prefer to see and if someone wants to pick it up, I'd be glad to merge it. Right now, I am just holding on in maintenance mode on this code and trying to keep it running. I agree it could be better re: your comments but I can't put more time into this. People are using this so please don't remove it.

**Comment by webknjaz** [comment]
@decentral1se if you don't have anything against GHA, I can submit a PR with it, mirroring what Drone does but with full GH integration. This seems easy.

**Comment by decentral1se** [comment]
@webknjaz  that would be nice, thanks for offering. Can you also maintain it?

**Comment by webknjaz** [comment]
I like to believe that it won't need much maintenance. But I can help out occasionally if need be. I'm mostly interested in scalable maintenance solutions these days, meaning that I'm likely to spend some time on automation that would be reused across similar projects so I'll probably do that at some point. But for now, I'll just send a PR as I see it.
The only thing needed from you would be to go to the repository settings and create a secret for that token used in the integration tests so it could be referenced from the GHA workflows.

**Comment by decentral1se** [comment]
OK, sounds fine! Opened https://github.com/ansible-community/molecule-hetznercloud/issues/38 to track :rocket:
