### ISSUE TITLE
💖 Project needs maintainers

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule-hetznercloud#43]
That is a call for finding some people that can maintain this project, ensuring that there is a CI/CD pipeline running and that the project does work with latest versions of molecule.

**Comment by decentral1se** [comment]
Yes apologies all, I'm not using molecule or this plugin anymore and am busy elsewhere in free software world.

I can help with handover or whatever, just @ me.

**Comment by ssbarnea** [comment]
@decentral1se No need to worry and thanks for the effort spent so far. With bit of luck we will have someone else to takeover.

**Comment by stefa2k** [comment]
Hey, I use this plugin a lot and just saw that molecule dropped support for it: https://github.com/ansible-community/molecule/pull/3322 What is necessary to get it in there again?

**Comment by ssbarnea** [comment]
@stefa2k That project does not have GHA pipelines configured so basically is not running any CI/CD integration. The first step would be to replicate the GHA pipelines that are used by other plugin projects. I am not inclined to review any change w/o seeing some job reporting.

I would suggest starting by copying the `.github/workflows` from molecule-podman plugin and see what happens. If you need help you can also find me on our matrix channel. Just be aware that you will need few hours to resurrect it.

**Comment by jooola** [comment]
Hello all :wave:, I am taking over the maintenance of this project.

Expect a new major release in the coming weeks.

Closing this as solved.
