### ISSUE TITLE
Debugging molecule runs which use this driver

### ISSUE THREAD

**Issue by till** [ansible-community/molecule-hetznercloud#9]
We run into issues time and time again where tests don't complete because instances either fail to start at all or e.g. molecule (Ansible) fails find SSH on the instance:

https://github.com/pycontribs/molecule-hetznercloud/blob/e3d14e0e37587d490096b4efde5eb2d4ea55608a/molecule_hetznercloud/cookiecutter/scenario/driver/hetznercloud/%7B%7Bcookiecutter.molecule_directory%7D%7D/%7B%7Bcookiecutter.scenario_name%7D%7D/create.yml#L81-L87

... or later on, fails to connect to the running instance via SSH.

We starting using pipelining, which helped some. But generally, it's really hard to debug this.

I suppose some of this is a platform issue. I am unable to debug this though, as we run 6 (or so) scenarios in each PR/merge build and it's literally another "scenario" every time. Their support has been saying "no issues" even when their status feed scrolls by with a multiple issues on different "cloud nodes".

I also noticed this:
https://docs.hetzner.cloud/#overview-rate-limiting

Is this elevated somehow? Or is this something that would need to be added to `hcloud_server`?

Was hoping someone had insights into how this could be made more transparent.

**Comment by decentral1se** [comment]
I actually run this in monorepos with 15+ roles which fire up 15+ hetzner boxes and it runs smooth and stable. I was having major issues until I realised that I actually have a hetzner box limit set on my account. Have you checked that you're not hitting your limit? Otherwise, you can do `MOLECULE_NO_LOG=False` and `MOLECULE_DEBUG=True` and get all the logs you need, no?

**Comment by till** [comment]
I want to say that 99% of all issues are fixed by a „let me re-run the build“.

So there, by adding more verbose output, I get nothing. When I always run with debug etc. it becomes somewhat challenging to spot the issue.

I‘ll definitely check the limit, however, say I am approaching/hitting the limit. Why would it only fail when it’s trying to connect via SSH and not when it creates the server?

**Comment by decentral1se** [comment]
> Why would it only fail when it’s trying to connect via SSH and not when it creates the server?

Yeah good point. It could be that your CI/CD is using paths that makes molecule overwrite SSH key paths or something? Connection details getting mixed up and Molecule thinking the old details are the new ones? That has happened before... not sure!

**Comment by till** [comment]
Since all of this runs containerized, we took out the key generation part from the playbook and inject our own "CI" ssh key. E.g. to be able to log into an instance and debug/troubleshoot in case it's needed. But yeah, at times, we literally go without issues for a week and then there are days where we constantly have to restart builds as they keep "timing out during the ssh connect".

So anyway, usually it's fixed by a restart. Which makes troubleshooting this with Hetzner support also cumbersome. Apparently they can't see anything at all, unless the instance is still running.

**Comment by decentral1se** [comment]
> we took out the key generation part from the playbook and inject our own "CI" ssh key. E.g. to be able to log into an instance and debug/troubleshoot in case it's needed.

Boom that is your issue for certain. And if you've customised the playbook you're already out on your own at this point... tore my hair out with something similar. You better step through some builds manually and try to debug what is happening. Can we close this ticket? Feel free to continue to discuss afterwards, I'll respond.

**Comment by till** [comment]
I am not entirely sure what you think the issue is?

**Comment by decentral1se** [comment]
You've customised your playbook from the default and replaced the SSH key logic with something custom which is now resulting in you having an SSH issue. I've given you the debugging tips that are available under Molecule. This isn't something that I can fix from this side.

**Comment by decentral1se** [comment]
Hey I'm gonna close this off, come and chat on the IRC room #ansible-molecule if you want to dig into this more.
